from datetime import date

from backend.core.business.timesheet_resolution.period_resolver import (
    resolve_timesheet_period,
)
from backend.core.business.timesheet_resolution.timesheet_finder import (
    find_timesheets_for_period,
)


AUTH_HEADER = "Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6ImFGa21LVkZjLTRXVjZzWENCdk5aa1hJNTA1WSIsImtpZCI6ImFGa21LVkZjLTRXVjZzWENCdk5aa1hJNTA1WSJ9.eyJhdWQiOiJhcGk6Ly83M2Y5YjJkMS04OTI5LTRmYzEtYTIyOC1kMzQ2YjllMzNlOWIiLCJpc3MiOiJodHRwczovL3N0cy53aW5kb3dzLm5ldC9iNGUxYjAyNi05Y2FhLTQxZmEtOTk1MC0zNzdiN2VjNDZhZGIvIiwiaWF0IjoxNzg0MDM2MzczLCJuYmYiOjE3ODQwMzYzNzMsImV4cCI6MTc4NDA0MDY5MCwiYWNyIjoiMSIsImFpbyI6IkFZUUFlLzhjQUFBQThhQ0xnTDhyN1lQaEJtekN0ZldocldEREZtZnpVMjZLS1cwK2ZCWHVRNWNsLzFzM1U1Z3ZQempSSTZzN3ZYTFVxR3psWDVmVUREMHFkUWVNaFc2MHNmOWFmZ3VtQ2FVYnNmdHZvZGl4amRLbGpjbTJqbnpUSURIbUQvT1BIaWRib3JVbThaekJZVDlXZ1h5cjlpMVVYWlF1V05LeTVCaTRBY3N6MUw1RVhqbz0iLCJhbXIiOlsicHdkIiwibWZhIl0sImFwcGlkIjoiNzNmOWIyZDEtODkyOS00ZmMxLWEyMjgtZDM0NmI5ZTMzZTliIiwiYXBwaWRhY3IiOiIwIiwiZmFtaWx5X25hbWUiOiJXZWRhIiwiZ2l2ZW5fbmFtZSI6Ik1vc3NhYWIiLCJpcGFkZHIiOiI0MS4yMjQuNS43OSIsIm5hbWUiOiJNb3NzYWFiIFdlZGEiLCJvaWQiOiJmNmNlZTVmMC01MmE3LTQ1ZTktODRlNC02MTdlMWYzZjIwY2UiLCJyaCI6IjEuQVJ3QUpyRGh0S3FjLWtHWlVEZDdmc1JxMjlHeS1YTXBpY0ZQb2lqVFJybmpQcHNBQUZjY0FBLiIsInNjcCI6IkZOTy5TZXJ2ZXIuQVBJIiwic2lkIjoiMDA2YmU5MWEtNGMyZC0yMzhhLTVhZWItYzVhNTU0NjhhMzcxIiwic3ViIjoiczJteV9NUmwtckF5VnNJWGlXNkhoZ1FkY0QyQTFGemtXLTJoNXlGNnBIWSIsInRpZCI6ImI0ZTFiMDI2LTljYWEtNDFmYS05OTUwLTM3N2I3ZWM0NmFkYiIsInVuaXF1ZV9uYW1lIjoibW9zc2FhYi53ZWRhQG1ldGFtLnRlY2giLCJ1cG4iOiJtb3NzYWFiLndlZGFAbWV0YW0udGVjaCIsInV0aSI6Il9CMXJRdjNyVzAtYnR2SVpzQk0xQUEiLCJ2ZXIiOiIxLjAiLCJ4bXNfZnRkIjoiSzZ1TGotUXJDdDRBdFMwSUhfbEt5ZHhhNC1yOFpPbndtY2pNRFp2ZzFMNEJkWE5sWVhOMExXUnpiWE0ifQ.HR1zsiqCDBRiMi03r47_WWEgy54TgV_Xi_Eo9Fvh_GMIwQF6mwW086oW_5Bz9QPhsSjkyueHyDa7hle96RG9ZUXEnNQMaRAVw_-MzE-YxCeNn2H5SvOkSu3_0edeWXBm5U63D1w7LA1UplN7QI3bH4cREbcOZ3L_-mRe2BDDLkOCGOQFUi2VbeqKNoUY_Zfi-96YbhiJ53JU71BJydNoCmq-huqtYcAugqDQfnwdrQFuPT44A5kPY6JKuT5WnFfehBWQpI8Tukjm_Tjm5k13wQ7peRiKbZYMzbLlzBnS8kT5qWaWdUH9buGvYhRExj0QOGQAergB50lw3yLP7kAN8Q"
RESOURCE_ID = "RES-3988"


period = resolve_timesheet_period(
    period_mode="current_week",
    reference_date=date(2026, 7, 14),
    source_expression="la feuille de cette semaine",
)

print("PERIOD:", period.model_dump())

result = find_timesheets_for_period(
    period=period,
    resource_id=RESOURCE_ID,
    auth_header=AUTH_HEADER,
)

print("LOOKUP:", result.model_dump())