import json

import httpx
from backend.tools.hub_functions import _get, hub_get_project_tasks

AUTH_HEADER = "Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6ImFGa21LVkZjLTRXVjZzWENCdk5aa1hJNTA1WSIsImtpZCI6ImFGa21LVkZjLTRXVjZzWENCdk5aa1hJNTA1WSJ9.eyJhdWQiOiJhcGk6Ly83M2Y5YjJkMS04OTI5LTRmYzEtYTIyOC1kMzQ2YjllMzNlOWIiLCJpc3MiOiJodHRwczovL3N0cy53aW5kb3dzLm5ldC9iNGUxYjAyNi05Y2FhLTQxZmEtOTk1MC0zNzdiN2VjNDZhZGIvIiwiaWF0IjoxNzg0MTk5MjAyLCJuYmYiOjE3ODQxOTkyMDIsImV4cCI6MTc4NDIwMzEyNSwiYWNyIjoiMSIsImFpbyI6IkFZUUFlLzhjQUFBQTNjaytsb2g4Ym4zNzYrdWtGN2xvVmxlUFhrbkdQRUFWMTlDZUc4cmNkZzN1V3JXRkRwWjlvVHlmZENYYXRPSHZEMVhuclhrNEk3TTdGWXlSU29RYTVidmx6T3QySTloQVNGRUwrMEVVelpMYmFHMjJmYUZ2c1pPNGlsdkVoNS9uTTV0REFKZks4S2lFM0tsa3NtdTA3OFExTE81OUFpaUFOenMwcGY2dURmUT0iLCJhbXIiOlsicHdkIiwibWZhIl0sImFwcGlkIjoiNzNmOWIyZDEtODkyOS00ZmMxLWEyMjgtZDM0NmI5ZTMzZTliIiwiYXBwaWRhY3IiOiIwIiwiZmFtaWx5X25hbWUiOiJXZWRhIiwiZ2l2ZW5fbmFtZSI6Ik1vc3NhYWIiLCJpcGFkZHIiOiI0MS4yMjguNjguMTAyIiwibmFtZSI6Ik1vc3NhYWIgV2VkYSIsIm9pZCI6ImY2Y2VlNWYwLTUyYTctNDVlOS04NGU0LTYxN2UxZjNmMjBjZSIsInJoIjoiMS5BUndBSnJEaHRLcWMta0daVURkN2ZzUnEyOUd5LVhNcGljRlBvaWpUUnJualBwc0FBRmNjQUEuIiwic2NwIjoiRk5PLlNlcnZlci5BUEkiLCJzaWQiOiIwMDZiZTkxYS00YzJkLTIzOGEtNWFlYi1jNWE1NTQ2OGEzNzEiLCJzdWIiOiJzMm15X01SbC1yQXlWc0lYaVc2SGhnUWRjRDJBMUZ6a1ctMmg1eUY2cEhZIiwidGlkIjoiYjRlMWIwMjYtOWNhYS00MWZhLTk5NTAtMzc3YjdlYzQ2YWRiIiwidW5pcXVlX25hbWUiOiJtb3NzYWFiLndlZGFAbWV0YW0udGVjaCIsInVwbiI6Im1vc3NhYWIud2VkYUBtZXRhbS50ZWNoIiwidXRpIjoidmNSeFUzYm9EazZ0NUsyS1I3Y2tBQSIsInZlciI6IjEuMCIsInhtc19mdGQiOiI1MGtLNzk4SmpJM0ZxYXU3eE5jMTA0bzREUjFPbXd2WTRoMTg1VGJ3TVpFQmRYTnpiM1YwYUMxa2MyMXoifQ.hTbeLknbI5PIyLn7wUdSsPygACk9JlZLbvLSvqjNC97yetuuTLg0A-MrdOZhI7uMv6a7hvPSHlmBwK2hiqc-RD5cvdllu3PDQHl5W7M7iueFVM5fcXdXuqA8ZQ6txn2gEqCGJ22CMevw3HWJV9Vo1MVc3aV7C2KfzIHFmleowzcTYOo1zvTav6-VcEGVMLRfHBXAHrm6BuePxS98iATNkxvSHUocN3e8GM8tHsI6WKRG-QhNysy5CHjNtTAibGNMX_qDufKUBn8QAhk19dOYAZkN-x_1SP0d5R9V89pHKTMXVvRY96YICCwqLod3oR27Flh3xG-lPOY5puJBnJNeXg"
url = "https://func-cc1-dev-met-app.azurewebsites.net/api/task/TSK-00596"

def parse_json(raw: str) -> dict:
    try:
        return json.loads(raw)
    except (TypeError, json.JSONDecodeError):
        return {}

tasks_payload = parse_json(
    hub_get_project_tasks(
        proj_id="PRJ-00109",
        auth_header=AUTH_HEADER,
    )
)

print(json.dumps(tasks_payload, indent=2))

